language: php
sudo: required
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm # on Trusty only

before_script:
  - sudo apt-get install -y libcurl4-openssl-dev
  - phpenv config-add php.ext.ini
#  - composer self-update
  - composer install --no-interaction

script: phpunit