language: php
sudo: required
dist: trusty
group: edge
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm # on Trusty only
  - nightly

before_install:
  - composer install

script: phpunit