language: php
sudo: required
dist: trusty
group: edge
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
#  - sudo apt-get install -y libcurl4-openssl-dev
  - phpenv config-add .php.ext.ini
#  - composer self-update
  - composer clear
  - composer install --no-interaction
  - phpenv rehash

script: phpunit