language: php
#sudo: required
dist: trusty

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - 'hhvm'

before_script:
#  - phpenv config-add .php.ext.ini
#  - composer self-update
#  - composer clear
  - composer install --prefer-source --no-interaction

script: phpunit